backend:
  name: github
  repo: nipunadhamma/live
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "data"
    label: "දත්ත පාලනය"
    files:
      - file: "data.json"
        label: "වෙබ් අඩවියේ තොරතුරු"
        name: "site_data"
        fields:
          - { label: "ළඟම එන පෝය දවස", name: "poya", widget: "string" }
          - { label: "දවසේ දහම් පණිවිඩය", name: "quote", widget: "text" }
          - { label: "හිරු උදාව (Sunrise)", name: "sunrise", widget: "string" }
          - { label: "හිරු බැසීම (Sunset)", name: "sunset", widget: "string" }
